apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epic-frontend-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/bioyeneye/epic-patient-app.git
    path: deployement/gitops
    targetRevision: main
  
  destination:
    server: https://kubernetes.default.svc
    namespace: epic-frontend-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m